"""add comment to orders and phone to users

Revision ID: 595f69ae7643
Revises: bf106b6afc31
Create Date: 2026-08-26 13:33:41.060791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595f69ae7643'
down_revision: Union[str, Sequence[str], None] = 'bf106b6afc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('store_users', sa.Column('contact_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_users', 'contact_number')
    op.drop_column('orders', 'comment')
    # ### end Alembic commands ###
