"""add delivery fields to orders

Revision ID: bf106b6afc31
Revises: 1cde376f31ce
Create Date: 2026-08-23 13:27:57.179969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf106b6afc31'
down_revision: Union[str, Sequence[str], None] = '1cde376f31ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'recipient_name')
    # ### end Alembic commands ###
